apiVersion: v1
kind: Service
metadata:
  name: customer-frontend
  labels:
    app: customer-frontend
spec:
  type: LoadBalancer
  selector:
    app: customer-frontend
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8075
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
spec:
  selector:
    matchLabels:
      app: customer-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      containers:
      - name: customer-frontend
        image: lonneke/customer-ms-ui:latest 
        ports: 
        - name: http
          containerPort: 8075