# APP DEPLOYMENT
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer-frontend
  name: customer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      containers:
      - image: lonneke/customer-ms-ui:latest
        name: customer-frontend
        ports:
        - containerPort: 80
      restartPolicy: Always

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-frontend
  name: customer-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customer-frontend
  type: NodePort