version: '2'
services:
  customer-ms-ui:
    image: lonneke/customer-ms-ui:latest
    environment:
        CUSTOMER_MS_ENDPOINT: 'http://129.213.126.223:8011/customer'
    ports:
      - '7792:80/tcp'
